### ISSUE TITLE
Improving bruga-music

### ISSUE THREAD

**Issue by connecteev** [Brugarolas/bruga-music#1]
Logging this as an "issue" - couldnt find another way to reach out.
@Brugarolas this is a phenomenal project. How does it only have 15 stars?
Though I'm noticing some minor bugs and lots of areas for improvement. Would you like me to suggest? Let me know if you like me to log issues or some other way to collaborate. I'm new to vue so I hope to dig into some of the code myself at some point after my other commitments are taken care of - but let me know if logging issues now would help.

**Comment by Brugarolas** [comment]
Hi @connecteev, thank you for your words!
I know there is room for improvement, this project is far from finished. Unfortunately, I have little time to work on it – I haven’t even released v1.0 yet. Of course I’d like you (or anybody) to report bugs, make suggestions or request new features. All help is appreciated! I have some issues already localized (page transition feels odd and styles are not responsive at all), but feel free to report anything else and I will try to fix it within a week or two.

**Comment by connecteev** [comment]
@Brugarolas awesome. Look forward to taking this project further, I will start to think about some improvements and log them as issues.

**Comment by connecteev** [comment]
@Brugarolas 

I do have a question about whether our visions are going to align. With this app, would it be possible to have an experience like dev.to/pod with podcasts hosted on anchor.fm, like this one? That's where my podcasts are going to be hosted, and I'm going to embed each individual episode into my app using an embed code like:

<iframe src="https://anchor.fm/potd/embed/episodes/Creating-Our-Own-Lives-evnuj/a-a19uj7" height="102px" width="400px" frameborder="0" scrolling="no"></iframe>
The anchor player will be embedded into my page, but I'm hoping the player you are working on will also have controls at the bottom bar (exactly like https://dev.to/softskillseng/episode-160-non-manager-1-1s-and-throwing-away-dev-learning when you press play).
Then when I navigate away from the podcast episode page (click on another link on the site, click back, etc), the bottom bar should persist and the podcast should keep playing.
